# Generated by Django 6.0.2 on 2026-02-16 09:45

import django.core.validators
import django.db.models.deletion
import liens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('code_unique', models.CharField(default=liens.models.generate_unique_code, editable=False, max_length=8, unique=True, verbose_name='Code unique')),
                ('actif', models.BooleanField(default=True, verbose_name='Profil actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du lien')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liens.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Lien',
                'verbose_name_plural': 'Liens',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
    ]
